// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cypilqllrdjfhcdzqmdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5cGlscWxscmRqZmhjZHpxbWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjU1NzIsImV4cCI6MjA2ODA0MTU3Mn0.nNwN4dyd_PbnhBy1MFe6muM0z8ST_img2EzuOuniHas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});